repositories:
  - name: "prometheus-community"
    url: "https://prometheus-community.github.io/helm-charts"
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: "grafana"
    url: "https://grafana.github.io/helm-charts"
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/prometheus
    version: 20.1.0
    values:
      - alertmanager:
          enabled: true
          persistence:
            size: 10Gi
          strategy:
            type: Recreate
        server:
          persistentVolume:
            size: 10Gi
          strategy:
            type: Recreate
          resources:
            limits:
              cpu: 400m
              memory: 1000Mi
            requests:
              cpu: 400m
              memory: 1000Mi
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.middlewares: "traefik-zeet-auth@kubernetescrd"
            hosts:
              - zeet-prometheus.{{ requiredEnv "CLUSTER_DOMAIN" }}
            tls:
              - hosts:
                  - zeet-prometheus.{{ requiredEnv "CLUSTER_DOMAIN" }}
        nodeExporter:
          tolerations:
            - effect: "NoSchedule"
              operator: "Exists"
        kube-state-metrics:
          metricLabelsAllowlist:
            - 'pods=[*]'
  - name: external-dns
    namespace: kube-system
    chart: external-dns/external-dns
    version: 1.13.1
    values:
    - sources:
        - service
      publishHostIP: true
      txtOwnerId: external-dns
      domainFilters:
        - {{ requiredEnv "CLUSTER_DOMAIN" }}
      provider: azure
      extraArgs:
      - --txt-wildcard-replacement=""
      serviceAccount:
        name: external-dns
        annotations:
          azure.workload.identity/client-id: {{ requiredEnv "DNS_MANAGER_IDENTITY_CLIENT_ID" }}
      podLabels:
        azure.workload.identity/use: "true"
      secretConfiguration:
        enabled: true
        mountPath: "/etc/kubernetes/"
        data:
          azure.json: |
            {
              "subscriptionId": "{{ requiredEnv "AZURE_SUBSCRIPTION_ID" }}",
              "resourceGroup": "{{ requiredEnv "AZURE_RESOURCE_GROUP" }}",
              "useWorkloadIdentityExtension": true
            }
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 12.0.7
    values:
      - deployment:
          replicas: 1
          terminationGracePeriodSeconds: 300
        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: {{ requiredEnv "CLUSTER_DOMAIN" }}.,*.{{ requiredEnv "CLUSTER_DOMAIN" }}.
        additionalArguments:
          - --entryPoints.web.proxyProtocol.trustedIPs=10.0.0.0/8
          - --entryPoints.websecure.proxyProtocol.trustedIPs=10.0.0.0/8
        ingressClass:
          enabled: true        
        logs:
          general:
            level: FATAL
          access:
            enabled: true
        resources:
          limits:
            cpu: 0.2
            memory: 0.4Gi
          requests:
            cpu: 0.2
            memory: 0.4Gi
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 10
          metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 70
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.13.0
    values:
      - installCRDs: true
        serviceAccount:
          annotations:
            azure.workload.identity/client-id: {{ requiredEnv "DNS_MANAGER_IDENTITY_CLIENT_ID" }}
        podLabels:
          azure.workload.identity/use: "true"
  - name: keda
    namespace: keda
    chart: kedacore/keda
    version: 2.11.2